### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by msylgj** [NateLol/natelol#1]
大佬,经过反复测试验证,发现6月1号提交3个commit之后的版本会导致无法上网的情况, 手动删除firewall配置中增加的以下内容后重启, 即可恢复正常.麻烦检查一下呗.
`config include 'beardropper'
	option type 'script'
	option path '/etc/beardropper.include'
	option reload '1'`

**Comment by NateLol** [comment]
6月1号的commit本来是想解决在防火墙页面点击重启防火墙的时候，之前的beardropper chain会丢失的问题的，现在好像出现了新的bug我已经把firewall相关的comment掉了。

等我有空测试了再添加吧。

多谢反馈！
